### ISSUE TITLE
Cesium_Air.glb not working

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/gltf-pipeline#106]
Using the model:

[Cesium_Air.glb.txt](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/330894/Cesium_Air.glb.txt)

I'll try to take a look soon.

**Comment by lasalvavida** [comment]
The bufferId in Cesium_Air.glb is currently `KHR_binary_glTF`, not just `binary_glTF`, so the buffer isn't loaded in `parseBinaryGltf, as per the [extension spec](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF), this fails because Cesium_Air.glb isn't a valid file.

**Comment by lilleyse** [comment]
Ah ok. It looks like COLLADA2GLTF exports correctly now, so I'm going to close this.

**Comment by pjcozzi** [comment]
Where did `Cesium_Air.glb` come from?  Can you update it?
