### ISSUE TITLE
gltf -> glb conversion breaks model

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/gltf-pipeline#296]
1. Download http://assets.agi.com/models/orbview3.gltf
2. Run `node bin/gltf-pipeline.js -i orbview3.gltf -o orbview3.glb -b`
3. Crash

```
Unhandled rejection TypeError: shaderOne.extras._pipeline.source.equals is not a function
    at shaderEquals (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\MergeDuplicateProperties.js:227:46)
    at Function.MergeDuplicateProperties.mergeShaders (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\MergeDuplicateProperties.js:189:17)
```

The problem is that `sharedEquals` assumes that `shaderOne.extras._pipeline.source` and `shaderTwo.extras._pipeline.source` are both buffers, but they are actually both strings in this case.

Because of this, I'm not sure where the bug actually is, should these values always be buffers?  Always be strings?  Or can they be either?

I feel like this is a bug we keep running into where we assume source is one thing and then we get a crash because it's another.

If I update the code to just do `===`, it no longer crashes, but the model loads incorrectly with bad textures.

CC @likangning93 @lilleyse

**Comment by likangning93** [comment]
The dataURI for the shaders object is `data:text/plain` base64 encoded, so it seems like it's a string instead of a buffer. I took a quick look, and I think the texture problem from using `===` is actually a `glb` issue... there's a separate problem where shaders sometimes behave differently between `gltf` and `glb`.

Updating the code to `===` and outputting embedded non-binary `gltf` seems to produce a model that looks just fine. Whoever tackles this should definitely still take a look at how `extras._pipeline.source` for shaders are loaded, though, make sure the result is consistent both when the `gltf` has embedded and external shaders.

**Comment by lilleyse** [comment]
This is just a missed case. @mramato your fix is the right one, and shaders should always be strings rather than buffers now.

This is what I see for the textures, before and after conversion:

![satellite](https://user-images.githubusercontent.com/915398/27774561-f304bd04-5f62-11e7-986a-15e08f28365e.png)

**Comment by lilleyse** [comment]
Oh never mind, I wasn't converting to glb. I also see a back texture.

**Comment by likangning93** [comment]
For some reason, the glb behaves differently in Sandcastle.

**Comment by mramato** [comment]
I can confirm the different behavior in the Composer Model Inspector that @likangning93 reports, so we can close this as soon as #297 is merged.

I wrote up a separate bug in a different repository to figure out the black texture issue.

**Comment by lilleyse** [comment]
Don't remember the bug, but this works in `master` fine.

![satelite](https://user-images.githubusercontent.com/915398/44127372-06b33bd4-a00b-11e8-89d6-a3c56ad10a5f.gif)
