### ISSUE TITLE
Provide a super simple way for engines to add support for spec gloss

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/gltf-pipeline#331]
See
* https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness/examples
* https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#best-practices

**Comment by emackey** [comment]
For what it's worth, the "lossless" conversion goes the other way.  Spec/Gloss is more flexible than Metal/Rough, and there is a direct, simple conversion from metal/rough to spec/gloss, but not the other way around.  See https://github.com/KhronosGroup/glTF/issues/696#issuecomment-250839212 and some [OSGjs sample code](https://github.com/cedricpinson/osgjs/blob/b4404ca0e9f0237709110e2a4dfeab533faaab90/examples/pbr/shaders/pbrReferenceFragment.glsl#L248-L255).

Basically the metallic map is used to `lerp` the baseColor, and the roughness channel is inverted to form glossiness.

```
// Pseudocode conversion from (baseColor, metallic, roughness) to (diffuse, specular, glossiness)

diffuse.rgb = baseColor.rgb * (1.0 - metallic)
specular.rgb = baseColor.rgb * metallic
glossiness = 1.0 - roughness
```

As such, there's no lossless "reverse" conversion, since diffuse and specular could be unrelated colors, there's no way to combine them into a sensible baseColor.

**Comment by pjcozzi** [comment]
@emackey I thought this stage would provide a super simple way for engines to add support for spec gloss.  What do you suggest?  Engines should just natively support both?  Or engines could natively support spec gloss and then convert metal rough to it?

**Comment by emackey** [comment]
Yes, I believe the accepted wisdom is that for engines that want to support both, the best practice is to "natively" support PBR in the form of spec/gloss, and have a simple transformation in the fragment shader to get there from metal/rough when needed.  You can see this is what OSGjs is doing.

I forgot to check what `glTF-WebGL-PBR` actually does about this issue, so I just looked at it now.  Here's the [relevant code there](https://github.com/KhronosGroup/glTF-WebGL-PBR/blob/a94655275e5e4e8ae580b1d95ce678b74ab87426/shaders/pbr-frag.glsl#L220-L223).  Looks like the transform from metal/rough to spec/gloss is already hard-coded in the frag shader.  We just need a way to make that transform conditional, so that the spec/gloss maps can drive those values directly, without using that hard-coded `0.04` in there.

**Comment by pjcozzi** [comment]
Gotcha, thanks!

**Comment by bghgary** [comment]
@emackey 
The `diffuseColor` and `specularColor` in the `glTF-WebGL-PBR` shader are inputs to the BRDF equations and are not the same as the diffuse and specular in the spec-gloss extension. Converting from the spec-gloss extension inputs to the BRDF inputs is documented near the end of [this section](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#specular---glossiness). The conversion from metal-rough to spec-gloss should be something similar to [this conversion function](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#specular---glossiness). The factor/texture combo also needs to be taken into account during the conversion.

@pjcozzi 
> provide a super simple way for engines to add support for spec gloss

Perhaps the title should be edited to avoid confusion.

**Comment by pjcozzi** [comment]
>> provide a super simple way for engines to add support for spec gloss
>
> Perhaps the title should be edited to avoid confusion.

Updated.

**Comment by emackey** [comment]
Started thinking about this again recently.  The links broke during the great extension folder re-org, here are updated links:

> The diffuseColor and specularColor in the glTF-WebGL-PBR shader are inputs to the BRDF equations and are not the same as the diffuse and specular in the spec-gloss extension. Converting from the spec-gloss extension inputs to the BRDF inputs is documented near the end of [this section](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness#specular---glossiness). The conversion from metal-rough to spec-gloss should be something similar to [this conversion function](https://github.com/KhronosGroup/glTF/blob/846a13bff8cfca3cf403598b0f7a409d5724b5e2/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/examples/convert-between-workflows-bjs/js/babylon.pbrUtilities.js#L12). The factor/texture combo also needs to be taken into account during the conversion.

Looking at the formulas at the bottom of that section, I see alpha is (1 - glossiness) squared, which is the same as the roughness-squared that glTF-WebGL-PBR uses.  The other formula is this:

> Cdiff = `diffuse.rgb * (1 - max(specular.r, specular.g, specular.b))`

Here it looks like we're making sure that the diffuse channel goes dark for "metals" (or anytime there's high specular, since this is not metal/rough workflow we're talking about).  But I'm confused, shouldn't a standard spec/gloss workflow already have this calculation baked into the supplied diffuse map?

For example, in WaterBottle's spec/gloss assets, one can clearly see a particular yellowish color of the bottle.  Some pixels have this color in the diffuse map, with black in the spec map.  Other pixels have this color in the spec map with black in the diffuse map.  This seems very akin to the metal/rough workflow where one base color has some metal areas and some non-metal areas.  But why would I take the spec/gloss version's diffuse map and re-multiply it by `(1 - max(specular.r, specular.g, specular.b))`?  It looks like that multiplication is already baked into the map.

**Comment by bghgary** [comment]
I really need to write up how I came up with the math. It's in my backlog. The gist of it is to solve for the workflow inputs given the two sets of equations for metallic-roughness and specular-glossiness. I will try to spend some time doing this.

> But I'm confused, shouldn't a standard spec/gloss workflow already have this calculation baked into the supplied diffuse map?

All the implementations of spec/gloss that I've seen does this to ensure energy conservation. As far as I know, it is not baked into the diffuse map.

> WaterBottle's spec/gloss assets

The original textures for the water bottle was authored with [metal/rough](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/sourceModels/WaterBottle). The spec/gloss textures were created using the [exact formula in the conversion function](https://github.com/bghgary/glTF-Tools-for-Unity/blob/master/UnityProject/Assets/Gltf/PbrUtilities.cs#L24) in the link you mentioned.

**Comment by emackey** [comment]
> The original textures for the water bottle was authored with metal/rough. The spec/gloss textures were created using the exact formula in the conversion function in the link you mentioned.

Oh I think I see.  The conversion from metal/rough to spec/gloss explicitly divides out the "oneMinusMaxSpecular" part, presumably expecting the runtime to multiply that back in later, as per the Cdiff formula above.

**Comment by emackey** [comment]
@lilleyse I think I understand what's needed in the shader.  If you or someone can get a branch of gltf-pipeline going with the mechanical hookup of specGloss, to get those textures/factors loaded into uniforms and the corresponding metal/rough textures/factors properly ignored for such models, I think the shader changes will be fairly simple from there.  Up to you if/when you want to prioritize this.

https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/25177db38c6c7874969acc02da339176d72b2607/lib/processPbrMetallicRoughness.js#L533-L536

In the above snippet, `roughness` is simply `1.0 - glossiness`, and `alpha` is still the square of that.  Glossiness comes from the alpha channel of the spec/gloss texture map, multiplied by the last component of the spec/gloss factor.  `f0` becomes identical to `specularColor`, which no longer uses `mix` and is now just the raw inputs from the specular texturemap's RGB channels multiplied by the specular factor.  The only gotcha is the `diffuseColor` above, which is the diffuse texture map multiplied by the diffuse factor, multiplied by `(1 - max(specular.r, specular.g, specular.b))`.

**Comment by lilleyse** [comment]
Moved to https://github.com/AnalyticalGraphicsInc/cesium/issues/6921, `gltf-pipeline` is no longer generating PBR shaders.
