### ISSUE TITLE
glTF file size after Draco compression

### ISSUE THREAD

**Issue by JohnnyPosi** [AnalyticalGraphicsInc/gltf-pipeline#370]
When I'm compressing the model using Draco:
`model.obj (8,000 KB) -> model.drc (204 KB)`

Using glTF Pipeline:
`model.gltf (304 KB) + model.bin (8,000 KB) -> modelDraco.gltf (200 KB) + modelDraco.bin (865 KB)`

So .gltf file is x5 bigger than .drc. Am I doing something wrong or just completely misunderstanding the purpose of the glTF file format?

I know it's a silly question, but it can probably help beginners like me. Thanks!

**Comment by felixmeissgeier** [comment]
@lilleyse  Does gltf w/ draco keep the model hierarchy? We work with models with multiple parts and parent/child relationships. Does your pipeline keep that structure?

Thanks!

**Comment by lilleyse** [comment]
Yes, both gltf-pipeline and Draco preserve the model hierarchy.

**Comment by felixmeissgeier** [comment]
really? We have troubles preserving the model hierarchy by just using Draco, because it seems to merge all sub-objects into one mesh? Do you mean the sub-object ids stored within Draco and the remapping afterwards using an external hierarchy-definition file or do you store each sub-object as separate Draco file?

**Comment by lilleyse** [comment]
Make sure you are on the [2.0 branch](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/tree/2.0) when testing Draco.

But yes, the Draco glTF extension applies compression on a per-primitive basis and does not alter the hierarchy or combine primitives.
