### ISSUE TITLE
conversion to GLB removes accessors

### ISSUE THREAD

**Issue by haehn** [AnalyticalGraphicsInc/gltf-pipeline#508]
I have the following .gtlf file

```
  "meshes": [
    {
      "primitives": [
        {
          "extras": {
            "properties": {
              "EmbeddingCoordinate": 3
            }
          },
          "attributes": {
            "POSITION": 0,
            "_NormalizedSignalEstimationError": 1
          },
          "indices": 2,
          "mode": 1
        }
      ]
    }
  ],
```
with accessors 0,1,2,3.

Now, after conversion to .glb, accessor 3 is removed since it is only referred to by an "extras" entry. 

What can I do to prevent the removal? I need to store additional acessors in the file that are part of "extras".

Thank you so much!

**Comment by lilleyse** [comment]
@haehn try passing in the flag `--keep-unused-elements` - the accessor might be getting being removed automatically because the code doesn't find any references to the accessor in the usual locations.

If that doesn't help then stages that remove unused elements will need to remove only the elements they know about. The stages themselves would need to be fixed.

Thanks for the bug report!

**Comment by haehn** [comment]
Thank you! It turned out that the --keepUnusedElements flag was ignored in the gltf-pipeline.js commandline tool. I added it to the options and now it works! See pull request. Thanks so much again.
